<h2><a title="[field:fulltitle/]" href="[field:arcurl/]"  target="_blank">[field:fulltitle/]</a></h2>
    		<ul>
    		<p>[field:info/]......</p>
    <p class="readmore"><a title="[field:fulltitle/]" href="[field:arcurl/]"  target="_blank">阅读全文>></a></p>
    <p class="dateview"><span>[field:pubdate function=MyDate('y-m-d',@me)/]</span><span>作者：[field:writer /]</span><span>文章来源：<a title="个人博客" href="/">个人博客</a>原创</span><span>分类：[[field:typelink/]]</span></p>
    	</ul>