<?php
$z[0]=Array("field","",65,88);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",93,114);
$z[1][4]['name']="pagexx";
$z[2]=Array("field","",202,224);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",264,322);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",340,372);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",420,452);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",520,552);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",612,648);
$z[7][4]['filename']="head.htm";
$z[8]=Array("channel","\r\n         <a href='[field:typeurl/]'>[field:typename/]</a>\r\n       ",704,812);
$z[8][4]['type']="son";
$z[9]=Array("field","",835,864);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n		<p class=\"ptit\"><b><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"  target=\"_blank\">[field:title/]</a></b></p>\r\n	   <p class=\"ptime\">发布时间：[field:pubdate function=MyDate('y-m-d',@me)/] 作者：[field:writer /] 分类：[field:typelink/]</p>\r\n<a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\"><img src=\"[field:picname/]\" class=\"imgdow\" alt=\"[field:fulltitle/]\"></a>\r\n	   <p class=\"pcon\">[field:description/]<a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">详细信息</a></P>\r\n	   <div class=\"line\"></div>\r\n    ",881,1472);
$z[10][4]['pagesize']="10";
$z[11]=Array("pagelist","",1533,1600);
$z[11][4]['listsize']="3";
$z[11][4]['listitem']="index pre pageno next end";
$z[12]=Array("arclist","\r\n		 <li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></li>\r\n         ",2176,2337);
$z[12][4]['row']="10";
$z[12][4]['titlelen']="32";
$z[13]=Array("arclist","\r\n		 <li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></li>\r\n         ",2451,2645);
$z[13][4]['sort']="hot";
$z[13][4]['orderby']="click";
$z[13][4]['row']="10";
$z[13][4]['titlelen']="42";
$z[14]=Array("global","",2964,2991);
$z[14][4]['name']="cfg_basehost";

?>